name: CountryCardioBoyz
favicon: null
layout_spectrum: 0.99593
typography_spectrum: 0.24309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090a0a'
    - '#cbedef'
    - '#74897e'
    - '#8f1a0f'
    - '#744f31'
  brandStrength: 0.8613396254368126
  lightness: 0.807994820876047
  saturation: 0.1776384529657662
  rhythmicContrast: 0.8472668593749404
purpose: []
